demo: proto changes with explicit routing headers for bigtable, spann…
googleapis/googleapis pull request #672
Opened 2021-08-31 20:02 UTC by viacheslav-rostovtsev

…er, firestore

2021-11-23 17:54 UTC, 0338383620 commented
> …er, firestore

2021-12-15 21:52 UTC, chanseokoh commented on google/api/routing.proto
> + This proto is here only until cl/378772749 is merged
cl/397839221 is merged, and `rounting.proto` is already present in the repo. Closing.

2021-12-15 21:53 UTC, chanseokoh commented on google/api/routing.proto
> + This proto is here only until cl/378772749 is merged
Actually, I don't have permissions to close this. @viacheslav-rostovtsev will you close this?

2023-04-09 14:03 UTC, Jorgeadrianmelgar requested changes

2023-04-09 14:03 UTC, Jorgeadrianmelgar commented on google/api/routing.proto
672

2023-04-09 14:03 UTC, Jorgeadrianmelgar commented on google/api/routing.proto
> +  // A field to extract the header key-value pair from
Y

2023-04-09 14:07 UTC, Jorgeadrianmelgar commented on google/api/BUILD.bazel
>      name = "service_proto",
@jorge

2023-04-26 09:25 UTC, closed without merging